services:
  Phauthentic\Symfony\ProblemDetails\Validation\ValidationErrorsBuilder:
    class: 'Phauthentic\Symfony\ProblemDetails\Validation\ValidationErrorsBuilder'

  Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactoryInterface:
    class: 'Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactory'

  Phauthentic\Symfony\ProblemDetails\FromExceptionEventFactoryInterface:
    class: 'Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactory'

  Phauthentic\Symfony\ProblemDetails\ExceptionConversion\ValidationFailedExceptionConverter:
    arguments:
      $validationErrorsBuilder: '@Phauthentic\Symfony\ProblemDetails\Validation\ValidationErrorsBuilder'
      $problemDetailsResponseFactory: '@Phauthentic\Symfony\ProblemDetails\FromExceptionEventFactoryInterface'
    tags: ['phauthentic.problem_details.exception_converter']

  Phauthentic\Symfony\ProblemDetails\ExceptionConversion\HttpExceptionConverter:
    arguments:
      $problemDetailsFactory: '@Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactoryInterface'
    tags: ['phauthentic.problem_details.exception_converter']

  Phauthentic\Symfony\ProblemDetails\ExceptionConversion\GenericExceptionConverter:
    arguments:
      $problemDetailsFactory: '@Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactoryInterface'
    tags: ['phauthentic.problem_details.exception_converter']

  Phauthentic\Symfony\ProblemDetails\ThrowableToProblemDetailsKernelListener:
    public: true
    arguments:
      $exceptionConverters: !tagged_iterator phauthentic.problem_details.exception_converter
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.exception', priority: 0 }
