services:
  Phauthentic\Symfony\ProblemDetails\Validation\ValidationErrorsBuilder:
    class: 'Phauthentic\Symfony\ProblemDetails\Validation\ValidationErrorsBuilder'

  Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactoryInterface:
    class: 'Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactory'

  Phauthentic\Symfony\ProblemDetails\FromExceptionEventFactoryInterface:
    class: 'Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactory'

  Phauthentic\Symfony\ProblemDetails\ExceptionConversion\ValidationFailedExceptionConverter:
    arguments:
      $validationErrorsBuilder: '@Phauthentic\Symfony\ProblemDetails\Validation\ValidationErrorsBuilder'
      $problemDetailsResponseFactory: '@Phauthentic\Symfony\ProblemDetails\FromExceptionEventFactoryInterface'

  Phauthentic\Symfony\ProblemDetails\ExceptionConversion\HttpExceptionConverter:
    arguments:
      $problemDetailsFactory: '@Phauthentic\Symfony\ProblemDetails\ProblemDetailsFactoryInterface'

  Phauthentic\Symfony\ProblemDetails\ThrowableToProblemDetailsKernelListener:
    arguments:
      $exceptionConverters:
        - '@Phauthentic\Symfony\ProblemDetails\ExceptionConversion\ValidationFailedExceptionConverter'
        - '@Phauthentic\Symfony\ProblemDetails\ExceptionConversion\HttpExceptionConverter'
        - '@Phauthentic\Symfony\ProblemDetails\ExceptionConversion\GenericExceptionConverter'
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.exception', priority: 0 }
